// BaseMain
plugins {
    id 'org.springframework.boot'
}

dependencies {
    // 启动模块需要 web starter
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // 依赖你的其他子模块（按需启用）
    implementation project(':module-common')
    implementation project(':module-base')
    implementation project(':module-stream')

    // 实验测试用（PushLatencyTest 需要 WS 客户端）
    testImplementation 'org.springframework.boot:spring-boot-starter-websocket'
}