// module-base
plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

dependencies {
    // 微信类
    implementation("com.github.binarywang:weixin-java-miniapp:4.7.0")

    // 业务模块不需要 Spring Boot 插件，只需要基础依赖
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'


    //  依赖公共包
    implementation project(':module-common')
}
