// module-stream
plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Redis 核心依赖（包含 Stream 相关类）
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    //  依赖公共包
    implementation project(':module-base')
    implementation project(':module-common')
}
