server:
  port: 8080
  tomcat:
    connection-timeout: 10000
program:
  name: sztu
  code: 10001

##服务监控
management:
  endpoints:
    web:
      exposure:
        include: 'loggers,health,prometheus'
middleware:
  redis: ${dev.localhost}
# 异步消息队列1
#  rocketmq: "192.168.18.79"
# 异步消息队列2
#  kafka: "192.168.1.132"
# 服务发现与查找
#  nacos: "192.168.18.79"
# 物联网服务
#  edge: "192.168.1.63"

spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  profiles:
    active: dev
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  data:
    ##redis
    redis:
      host: ${middleware.redis}
      port: 6379
      password: ${passwd.redis}
      database: 0

# 分布式定时任务
#xxl:
#  job:
#    admin:
#      addresses: http://${dev.localhost}/xxl-job-admin #xxl-job服务地址
#    accessToken: kN7yG0tM0oG6jN4x
#    executor:
#      appname: ${program.name}-${service.name}-${spring.profiles.active}
#      address:
#      ip:
#      port: 9999
#      jobgroup: ${server.servlet.xxl-job-group}
#      logpath: /data/applogs/xxl-job/jobhandler
#      logretentiondays: 30

playwright:
  pool:
    # 连接池大小
    pool-size: 100
    # 单个playright请求超时时间（单位：秒）
    timeout-reqest-duration: 10
    # 获取超时时间（单位：秒）
    timeout-poll-seconds: 5
    # 是否隐藏 UI 界面
    headless: false
    # 是否忽略 HTTPS 证书错误（自签名证书、过期证书）
    ignore-https-errors: true
    browser-type: chromium
    viewport-width: null
    viewport-height: null
    # 爬虫经常需要带的 —— User-Agent，网站经常有的反爬检测
    user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36

sztu:
  constant:
    projectOrBrandName: ${program.name}
    projectOrBrandCode: ${program.code}
    projectName: ${program.name}
    environment: ${spring.profiles.active}
